### ISSUE TITLE
broken links in the article

### ISSUE THREAD

**Issue by elisim** [omry/hydra-article-code#1]
Hi,

The links under "Final Words" section are broken:

![image](https://user-images.githubusercontent.com/17675462/113720813-abe60880-96f7-11eb-9e4b-3789f3d4f8f9.png)

(dynamic tab completion and automatic configuration of the Python logging subsystem).

When clicking:

![image](https://user-images.githubusercontent.com/17675462/113720974-ccae5e00-96f7-11eb-998f-ef18d9b80fce.png)

Thank you,
Eli

**Comment by omry** [comment]
Hi Eli,
Thanks for reporting.

The correct links are:
https://hydra.cc/docs/0.11/tutorial/tab_completion
https://hydra.cc/docs/0.11/tutorial/logging

**Comment by omry** [comment]
Note that the article is describing Hydra 0.11. You should use Hydra 1.0 now, and if you are feeling advantageous even the Hydra 1.1 dev release (which will become a release candidate soon).

**Comment by omry** [comment]
Links are fixed, thanks again.

**Comment by elisim** [comment]
Thank you
